import type { SourceType } from "@/lib/collectors/types";

export type CommunitySourceCatalogEntry = {
  id: string;
  name: string;
  description: string;
  type: SourceType;
  lane: "free" | "byok" | "paid";
  config: Record<string, unknown>;
  category: string;
  rulesUrl: string;
};

/** Individually selectable sources; installation enforces the workspace's source cap. */
export const COMMUNITY_SOURCE_CATALOG: readonly CommunitySourceCatalogEntry[] = [
  { id: "hn-ai-coding", name: "Hacker News AI coding", description: "Developer discussions about coding assistants. Research briefs only.", type: "hn", lane: "free", config: { queries: ["AI coding", "coding agent"], maxPages: 1 }, category: "Developer discussions", rulesUrl: "https://news.ycombinator.com/newsguidelines.html" },
  { id: "hn-agent-evaluation", name: "Hacker News agent evaluation", description: "Evaluation, reliability and agent tooling. Research briefs only.", type: "hn", lane: "free", config: { queries: ["agent evaluation", "LLM evaluation"], maxPages: 1 }, category: "Evaluation", rulesUrl: "https://news.ycombinator.com/newsguidelines.html" },
  { id: "dev-ai", name: "DEV.to AI", description: "Public AI development posts and tutorials.", type: "rss", lane: "free", config: { feedUrl: "https://dev.to/feed/tag/ai" }, category: "Developer feeds", rulesUrl: "https://dev.to/code-of-conduct" },
  { id: "dev-llm", name: "DEV.to LLM", description: "Public LLM implementation and tooling posts.", type: "rss", lane: "free", config: { feedUrl: "https://dev.to/feed/tag/llm" }, category: "Developer feeds", rulesUrl: "https://dev.to/code-of-conduct" },
  { id: "dev-langchain", name: "DEV.to LangChain", description: "Public LangChain implementation experience.", type: "rss", lane: "free", config: { feedUrl: "https://dev.to/feed/tag/langchain" }, category: "Developer feeds", rulesUrl: "https://dev.to/code-of-conduct" },
  { id: "lobsters", name: "Lobsters developer discussions", description: "Public technology discussions; broad feed, filter for product relevance.", type: "rss", lane: "free", config: { feedUrl: "https://lobste.rs/rss" }, category: "Developer discussions", rulesUrl: "https://lobste.rs/about" },
  { id: "simon-willison", name: "Simon Willison", description: "Practical AI development, tools and engineering notes.", type: "rss", lane: "free", config: { feedUrl: "https://simonwillison.net/atom/everything/" }, category: "Research feeds", rulesUrl: "https://simonwillison.net/about/" },
  { id: "huggingface-blog", name: "Hugging Face blog", description: "Public open-model ecosystem announcements and tutorials.", type: "rss", lane: "free", config: { feedUrl: "https://huggingface.co/blog/feed.xml" }, category: "Research feeds", rulesUrl: "https://huggingface.co/code-of-conduct" },
  { id: "huggingface-forum", name: "Hugging Face public forum", description: "Public Discourse questions across model and tooling projects.", type: "rss", lane: "free", config: { feedUrl: "https://discuss.huggingface.co/latest.rss" }, category: "Public forums", rulesUrl: "https://discuss.huggingface.co/guidelines" },
  { id: "openai-forum", name: "OpenAI developer forum", description: "Public Discourse developer questions; no authenticated categories.", type: "rss", lane: "free", config: { feedUrl: "https://community.openai.com/latest.rss" }, category: "Public forums", rulesUrl: "https://community.openai.com/guidelines" },
  { id: "latent-space", name: "Latent Space", description: "Public AI engineering newsletter posts.", type: "substack", lane: "free", config: { feedUrl: "https://www.latent.space/feed", maxResponseBytes: 3_000_000 }, category: "Public newsletters", rulesUrl: "https://www.latent.space/about" },
  { id: "ahead-of-ai", name: "Ahead of AI", description: "Public machine learning and LLM research explanations.", type: "substack", lane: "free", config: { feedUrl: "https://magazine.sebastianraschka.com/feed", maxResponseBytes: 3_000_000 }, category: "Public newsletters", rulesUrl: "https://magazine.sebastianraschka.com/about" },
  { id: "import-ai", name: "Import AI", description: "Public AI research and ecosystem reporting.", type: "substack", lane: "free", config: { feedUrl: "https://importai.substack.com/feed" }, category: "Public newsletters", rulesUrl: "https://importai.substack.com/about" },
  { id: "interconnects", name: "Interconnects", description: "Public model research and AI ecosystem analysis.", type: "substack", lane: "free", config: { feedUrl: "https://www.interconnects.ai/feed", maxResponseBytes: 3_000_000 }, category: "Public newsletters", rulesUrl: "https://www.interconnects.ai/about" },
  { id: "github-langgraph", name: "LangGraph GitHub issues", description: "Public agent orchestration problems and feature requests.", type: "github", lane: "free", config: { query: "repo:langchain-ai/langgraph is:open", maxPages: 1 }, category: "GitHub issues", rulesUrl: "https://github.com/langchain-ai/langgraph" },
  { id: "github-langchain", name: "LangChain GitHub issues", description: "Public framework integration problems and feature requests.", type: "github", lane: "free", config: { query: "repo:langchain-ai/langchain is:open", maxPages: 1 }, category: "GitHub issues", rulesUrl: "https://github.com/langchain-ai/langchain" },
  { id: "github-llamaindex", name: "LlamaIndex GitHub issues", description: "Public retrieval and data-agent implementation issues.", type: "github", lane: "free", config: { query: "repo:run-llama/llama_index is:open", maxPages: 1 }, category: "GitHub issues", rulesUrl: "https://github.com/run-llama/llama_index/blob/main/CONTRIBUTING.md" },
  { id: "github-openai-agents", name: "OpenAI Agents SDK GitHub issues", description: "Public agent SDK questions and reliability problems.", type: "github", lane: "free", config: { query: "repo:openai/openai-agents-python is:open", maxPages: 1 }, category: "GitHub issues", rulesUrl: "https://github.com/openai/openai-agents-python/blob/main/CONTRIBUTING.md" },
  { id: "github-promptfoo", name: "Promptfoo GitHub issues", description: "Public evaluation and testing workflow issues.", type: "github", lane: "free", config: { query: "repo:promptfoo/promptfoo is:open", maxPages: 1 }, category: "Evaluation", rulesUrl: "https://github.com/promptfoo/promptfoo/blob/main/CONTRIBUTING.md" },
  { id: "so-langchain", name: "Stack Overflow LangChain", description: "LangChain troubleshooting with bounded existing-answer context. Briefs only.", type: "stackoverflow", lane: "free", config: { query: "langchain", tagged: "langchain", includeReplies: true, maxPages: 1 }, category: "Troubleshooting", rulesUrl: "https://stackoverflow.com/help/ai-policy" },
  { id: "so-openai", name: "Stack Overflow OpenAI API", description: "Public API troubleshooting questions. Research briefs only.", type: "stackoverflow", lane: "free", config: { query: "openai", tagged: "openai-api", includeReplies: true, maxPages: 1 }, category: "Troubleshooting", rulesUrl: "https://stackoverflow.com/help/ai-policy" },
  { id: "reddit-localllama", name: "Reddit LocalLLaMA", description: "Public local-model and inference conversations; provider access required.", type: "reddit", lane: "byok", config: { subreddit: "LocalLLaMA", query: "agent tooling", limit: 10 }, category: "Reddit communities", rulesUrl: "https://www.reddit.com/r/LocalLLaMA/about/rules/" },
  { id: "reddit-langchain", name: "Reddit LangChain", description: "Public framework and agent building discussions.", type: "reddit", lane: "byok", config: { subreddit: "LangChain", query: "agent evaluation", limit: 10 }, category: "Reddit communities", rulesUrl: "https://www.reddit.com/r/LangChain/about/rules/" },
  { id: "reddit-openai", name: "Reddit OpenAI", description: "Public OpenAI tooling conversations; check relevance and venue rules.", type: "reddit", lane: "byok", config: { subreddit: "OpenAI", query: "developer tools", limit: 10 }, category: "Reddit communities", rulesUrl: "https://www.reddit.com/r/OpenAI/about/rules/" },
  { id: "reddit-ai-agents", name: "Reddit AI Agents", description: "Public agent workflow and implementation conversations.", type: "reddit", lane: "byok", config: { subreddit: "AI_Agents", query: "evaluation", limit: 10 }, category: "Reddit communities", rulesUrl: "https://www.reddit.com/r/AI_Agents/about/rules/" },
  { id: "reddit-machinelearning", name: "Reddit MachineLearning", description: "Public ML tooling discussions; strict community rules apply.", type: "reddit", lane: "byok", config: { subreddit: "MachineLearning", query: "evaluation tooling", limit: 10 }, category: "Reddit communities", rulesUrl: "https://www.reddit.com/r/MachineLearning/about/rules/" },
  { id: "alexandria-developer", name: "Alexandria developer discovery", description: "Paid indexed developer passages for grounding; not buying-intent proof.", type: "web_search", lane: "paid", config: { provider: "firecrawl-developer-index", capability: "search", query: "AI agent evaluation workflow", maxResults: 10, passages: 1 }, category: "Paid research", rulesUrl: "https://www.firecrawl.dev/alexandria/firecrawl-developer-index" },
  { id: "alexandria-langgraph", name: "Alexandria LangGraph issues", description: "Opt-in paid repository dataset; official GitHub collection is available free.", type: "web_search", lane: "paid", config: { provider: "github-com", capability: "repositories/issues", repo: "langchain-ai/langgraph", maxResults: 10, maxPages: 1 }, category: "Paid research", rulesUrl: "https://github.com/langchain-ai/langgraph" },
  { id: "linkedin-indexed", name: "LinkedIn indexed public posts", description: "Paid Scavio Google snippets; partial coverage, no private or logged-in content.", type: "linkedin", lane: "paid", config: { query: "AI developer tools evaluation", maxPages: 1, maxResults: 10 }, category: "Paid research", rulesUrl: "https://www.linkedin.com/legal/professional-community-policies" },
  { id: "x-ai-developer-tools", name: "X AI developer tools", description: "Opt-in Scavio public posts with optional Grok significance review.", type: "x", lane: "paid", config: { query: "AI developer tools", limit: 10 }, category: "Paid research", rulesUrl: "https://help.x.com/en/rules-and-policies/x-rules" },
];
